### ISSUE TITLE
receive.ino in examples is wrong?

### ISSUE THREAD

**Issue by raess1** [fmilburn3/ESP-NOW#1]
Hi, was trying to get the hello world demo to work. It looks like the receive.ino is also a sender?

**Comment by fmilburn3** [comment]
Oops….  It looks like I posted an early version with errors.  It should not be a sender.  I looked back and was not careful with the library management of this.  I played around with it some more after putting this on github and did not do updates.  I am going to post the latest that I find on my local machine but it looks like it was done with an ESP32 instead of the ESP8266.  Most likely the pin definitions for example LEDs might need to be changed.
